optimist        = require('optimist')
workerTypes = require('./lib/worker_types')

ascii = """
                    .
           .  .  ~D888ND. .
          ..,+:::=?$NNNNNNM..  ...
           .?$ZZZZO8DNNNNNNNDNND..
          . ?O8MNNNNNNNNNNMNNNMMMNMMMD+,:.
           ..$MNNNNNNDDDNNMMNMNNNNNNMDZ77I+~
           ..M+8NNMD8OOO8DNNNNNNNNNNNDI?7?+~:. ..+:+,~=..
          ..ONDNMOO8$=$ZD88MNNNNNNDND88:.::=,:~~+~,:++=~
          .N8?O7O$$MM=NMNO8MMMN.8DND8Z7D?~,=:7~,:~~=++?$.  .
          .DD7ZM.7NZM..,.,,,...M.,NDNNNNDODD8D+~~I+=++IO$=+?.
        ..ZDDN,DDNMDZ~.~::,:~=~,.Z8O8DDD8D8787+IODNZDN~77III..
          DDNNNM.DM.=I,~+++++=::Z8NDNDDNND.OO=$OII$MNMO+$?ID.
         .8NDMDNOMI,:~=+I?I+?78OZ~8DNMMMNN..?D7Z:I?NMDD?I77D$
        ..ZONNMNMN::,++=III?I$DDZDMMDO8DNNMN.IMM?MD8NMM+I7OZ$
        .NNMNDMMMOD==+$+7877??78NNOOODOOMMMMNNNDDD88MMMNII7N$+..
        ,8NNM8MMNM8N+~?$II77$77DMMDM88ZD8DDNNNNDDDDDNNNN8Z7OZI?.
        =$ZNDNDMMMMMN+7I$$ONMMMMMMM8DDDDODNNDD8NDDDDNNNNM8NOO?I?..
        O8ZZMNN8MMMNMMMMNMMMNMMMMMDDDDDDDDDDNNODNNDNNNMNDNDDD8II
        ZOZZZ8O8MMMMMMMMMNMMMMMMMNNNDNDDDDNDNDMNNNNNNMMNMMDDD$$I7.
      .,$OOO8ID8MMMMMMMMMMMMMMNNNNDDNNNNDDDNNDDDNNMMMMMNNNDDD$+:..
       ZZZO8O8ZMNMMMMMMMMMMMMMNNNDDDDNDNNN8?I=$?8MMNNNDDDDDDDD$
      .$Z888OO8$MMMMMMNMMMMMNMNNNND8D+DDO77IOZO7=~INNNNDDDDDNND$..
      .7ZZD$O88MOMMMMMMMMMMNNNNNNNDDDMDNO$ZD8OZZ~+~NNNNNDDDNMN8O.
      .ZZOOO8Z8OODMMMMNMM8NNNNNNNNMMMMMD$7ZDD8Z$~::?NNN?DDDMDD8$
      .ZZOOOD8D8MOMMMMMM8NNNNMMMMMNMMMMZNO77NZZ7+:+D8D8NDDMDD8$. .
      .ZZZOOOM8M88MMMMMMNNNNNMNNNNNNNNNMNNOO?7Z8==ZD8NNNNNDDD87I
      .ZOOOZOMMMMMMMMMNNNMMMMNMMMNMMOMNDMMMD8$?$78NDDDNNMNDDDO8,.
      ?ZOOOOO8MNNNNMMNNNNNNNNNNMMMMDNMNNMMM8MZ8MMNDMMNNNNNDD88O.
    ..$OOOZZZDD$NNMMNNNNNNNMMN8D88DDNMMMMMMDDMMMMDDNNNM8DNDDD8I.
     $ZOOOZZZONDN8NMMNMMMNMNDNDDZODDNDOMMNNNMMMMDDDNNNODNDOZ?:.
    .7ZO8ZZ8$$MMMMNMNNNMNNNZ88DOOONMNMNNNMNNMMNDD8NNNNND8ZI==...
    .ZO8OO$$$$Z$7D8MMMNNNNNNNNND8NDMMMNNNMNNNMDD8DDDNNDDDO:..
     O8OOO$7ZOOZ8?DN8MMMNNMNMMMMNNNMMMNMNNNNNDNDDDDDD~::::,.......
     7$OOO$NOOONNNMMDMNNNNMMMNNMMMMMMMMNNNMNNNNNDDD8O~~~:::,,,......
      ..ZZZ$O8MNM8NMNNNMNNNNNMMMMMMMMMMMMNMMMMNNDD88=~~~~::,,,......
        .ZO$NMNNNNNNNMNNDNNNNNMMMMMMMMMMMMNNMNNNDD8I+==~~,,,,,,,.....
         .OZMMNDNNNNNMNNNMMNNMMMMMMMMMMMMMNMMMNNNDO+~~:::::,,,,,....
        ..,88D8NNNNNNNNNNMM8NMMMMMMMMMMMMMMMMMMNND==~~~~~:::,,,,...
      ...,.,,DDODNNMNNNNNMMOMMMMMMMMMMMMMMMMMNNNNZ===~~~:~:::,,..
      ..,,,::::7ZODD88NNNNMMMMMDDDDDDDDD8O$77IOOO7=~~~~~:::::,..
        .,::::~~=7NDON8NNM$$$$$$$$$77$$$777777Z88==~~~~::::,.....
         ..,.,,,,:~??777777777777I7III???++++?++===~=~::,.....
             ,,,,::,::::::::::::::~~~~~~========~=~~~:,,... .
               .,,,,,,,,,,,,,,,,:,:,,:,,:::~~:~:::,......


"""

console.log ascii

argv = optimist.parse(process.argv)
if !argv.type? or !workerTypes[argv.type]?
  console.log 'Please specify a valid type of worker to spawn with the --type parameter.'
  console.log 'See worker_types for the list of workers.'
  console.log ''
  console.log 'Example parameter: --type=fileQueuer'
else
  workerTypes[argv.type].run()